config/routes.rb
Flashcards::Application.routes.draw do
  root 'dashboard/cards#home'
  post "search" => "dashboard/cards#check"

  scope module: 'dashboard' do
    resources :users, :cards
    resources :decks do
      post 'current_deck', on: :member
    end
  end

  scope module: 'home' do
    resources :user_sessions
  end

  get  'login'  => 'home/user_sessions#new',     :as => :login
  post 'logout' => 'home/user_sessions#destroy', :as => :logout

  get "oauth/callback" => "home/oauths#callback"
  get "oauth/:provider" => "home/oauths#oauth", :as => :auth_at_provider

  

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/card.rb
class Card < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :user
  belongs_to :deck

  validates :original, :translated, :user_id, :deck_id, presence: true
  validate :valid_combo
  before_create :set_default_review

  def set_default_review
    self.review = DateTime.now
  end

  def valid_combo
    if original.downcase == translated.downcase
      errors.add(:translated, "translated not equal original")
    end
  end

  scope :overdue, -> { where("review <= ?", DateTime.now) }

  def self.random_card
    overdue.order('RANDOM()').take
  end

  def check_translation(answer)
    update_params = SuperMemo.execute(review, original, answer, efactor, repeat, interval, quality)
    update(update_params)
  end
  
  def notify_train_card
    overdue.each do |card|
      NotificationsMailer.card_notice(card).deliver_now
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def home
    @card = if current_user.deck_id
      current_user.cards.where(deck_id: current_user.deck_id).random_card
    else
      current_user.cards.random_card
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def check
    @card = current_user.cards.find_by(id: params[:card_id])
    @card.check_translation(params[:answer])
    if @card.quality == 4
      flash[:notice] = (t '.notice1')
    elsif @card.quality == 3
      flash[:notice] = "#{params[:answer]} - #{t('.notice2')} [#{@card.original} - #{@card.translated}]"
    else @card.quality == 2
      flash[:alert]  = "#{params[:answer]} - #{t('.alert')} [#{@card.original} - #{@card.translated}]"
    end 
    redirect_to :back
  end

  def index
    @cards = current_user.cards
  end

  def show
  end

  def new
    @card = current_user.cards.build
  end

  def edit
  end

  def create
    @card = current_user.cards.create(card_params)
    @card.save ? (redirect_to @card) : (render 'new')
  end

  def update
    @card.update(card_params) ? (redirect_to @card) : (render 'edit')
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end

  private
    def set_user
      @card = current_user.cards.find_by(id: params[:id])
      redirect_to cards_path if @card.nil?
    end

    def card_params
      params.require(:card).permit(:original, :translated, :review, 
      :avatar, :remove_avatar, :deck_id)
    end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def home
    @card = if current_user.deck_id
              current_user.cards.where(deck_id: current_user.deck_id).random_card
            else
              current_user.cards.random_card
            end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def check
    @card = current_user.cards.find_by(id: params[:card_id])
    @card.check_translation(params[:answer])
    if @card.quality == 4
      flash[:notice_true] = (t '.notice1')
    elsif @card.quality == 3
      flash[:notice_typo] = "#{params[:answer]} - #{t('.notice2')} [#{@card.original} - #{@card.translated}]"
    elsif @card.quality == 2
      flash[:notice_false]  = "#{params[:answer]} - #{t('.alert')} [#{@card.original} - #{@card.translated}]"
    end 
    redirect_to :back
  end

  def index
    @cards = current_user.cards
  end

  def show
  end

  def new
    @card = current_user.cards.build
  end

  def edit
  end

  def create
    @card = current_user.cards.create(card_params)
    @card.save ? (redirect_to @card) : (render 'new')
  end

  def update
    @card.update(card_params) ? (redirect_to @card) : (render 'edit')
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end

  private
    def set_user
      @card = current_user.cards.find_by(id: params[:id])
      redirect_to cards_path if @card.nil?
    end

    def card_params
      params.require(:card).permit(:original, :translated, :review, 
      :avatar, :remove_avatar, :deck_id)
    end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  def current_deck
    current_user.update_attributes(deck_id: params[:id])
    redirect_to root_path
  end

  def index
    @decks = current_user.decks
  end

  def show
  end

  def new
    @deck = current_user.decks.build
  end

  def edit
  end

  def create
    @deck = current_user.decks.create(deck_params)
    @deck.save ? (redirect_to @deck) : (render 'new')
  end

  def update
    @deck.update(deck_params) ? (redirect_to @deck) : (render 'edit')
  end

  def destroy
    @deck.destroy
    redirect_to decks_path
  end

  private
    def set_deck
      @deck = current_user.decks.find_by(id: params[:id])
      redirect_to decks_path unless @deck
    end

    def deck_params
      params.require(:deck).permit(:name)
    end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :show]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
      if @user.save
        auto_login(@user)
        redirect_to @user, notice: (t '.notice')
      else
        render action: 'new' 
      end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: (t '.notice')
    else
      render action: 'edit' 
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :deck_id, :locale)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/dashboard/cards/_form.html.erb
<%= simple_form_for @card do |f| %>
  <%= f.input :original,   label: t('original_text') %>
  <%= f.input :translated, label: t('translated_text') %>
  <%= f.association :deck, collection: current_user.decks, label: t('deck') %>
  <%= image_tag @card.avatar_url(:thumb) if @card.avatar? %>
  <%= f.input  :avatar, label: t('avatar') %>
  <%= f.input  :remove_avatar, as: :boolean if @card.avatar? %>
  <%= f.button :submit, t('create_card'), class: "btn btn-warning" %>
<% end %>

app/views/dashboard/cards/_trainer_form.html.erb
<div class="text-center">
  <% if @card %>
    <h2 class="text-muted"><%= @card.translated %></h2>
    <p><%= image_tag @card.avatar_url  %></p>
    <%= form_tag search_path, remote: true do %>
      <%= hidden_field_tag(:card_id, @card.id) %>
      <%= text_field_tag   :answer %>
      <%= submit_tag t('check_answer'), class: "btn btn-warning" %>
    <% end %>
  <% end %>
  <p class="text-success"><%= flash[:notice_true] %></p>
  <p class="text-warning"><%= flash[:notice_typo] %></p>
  <p class="text-danger"><%= flash[:notice_false]  %></p>
</div>

app/views/dashboard/cards/edit.html.erb
<h3><%= t('edit') %></h3>
<%= render 'form' %>

app/views/dashboard/cards/home.html.erb
<div id='trainer'>
  <%= render 'trainer_form' %>
</div>

app/views/dashboard/cards/home.js.erb
+$("#trainer").html("<%= j render('trainer_form') %>");

app/views/dashboard/cards/index.html.erb
<table class="table table-striped table-condensed">
  <tr>
    <th><%= t 'original_text'   %></th>
    <th><%= t 'translated_text' %></th>
    <th><%= t 'date_review'    %></th>
    <th><%= t 'deck'            %></th>
    <th><%= t 'avatar'          %></th>
  </tr>

  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original   %></td>
      <td><%= card.translated %></td>
      <td><%= card.review     %></td>
      <td><%= card.deck.name  %></td>
      <td><%= image_tag card.avatar_url(:thumb) %></td>
      <td><%= link_to t('edit'), edit_card_path(card) %></td>
      <td><%= link_to t('delete'),  card_path(card),
              method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/dashboard/cards/new.html.erb
<h3><%= t 'new_card' %></h3>
<%= render 'form' %>

app/views/dashboard/cards/show.html.erb
<p>
  <strong><%= t 'original_text' %></strong>
  <%= @card.original %>
</p>
 
<p>
  <strong><%= t 'translated_text' %></strong>
  <%= @card.translated %>
</p>

<p>
  <strong><%= t 'date_review' %></strong>
  <%= @card.review %>
</p>

<p>
  <strong><%= t 'deck' %></strong>
  <%= @card.deck.name %>
</p>

<p>
  <strong><%= t 'avatar' %></strong>
  <%= image_tag @card.avatar_url(:thumb) %>
</p>