config/routes.rb
Flashcards::Application.routes.draw do
  root 'dashboard/cards#home'
  post "search" => "dashboard/cards#check"

  scope module: 'dashboard' do
    resources :users, :cards
    resources :decks do
      post 'current_deck', on: :member
    end
  end

  scope module: 'home' do
    resources :user_sessions
  end

  get  'login'  => 'home/user_sessions#new',     :as => :login
  post 'logout' => 'home/user_sessions#destroy', :as => :logout

  get "oauth/callback" => "home/oauths#callback"
  get "oauth/:provider" => "home/oauths#oauth", :as => :auth_at_provider

  

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= t :flashcards %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

  <div class="container">
    <div class="page-header">
      <nav>
        <ul class="nav nav-pills pull-right">
          <% if current_user %>
            <li role="presentation"><%= link_to t('edit_profile'), edit_user_path(current_user.id) %></li>
            <li role="presentation"><%= link_to t('sign_out'), :logout, method: :post %></li>
          <% else %>
            <li role="presentation"><%= link_to 'en', login_path(locale: 'en') %></li>
            <li role="presentation"><%= link_to 'ru', login_path(locale: 'ru') %></li>
            <li role="presentation"><%= link_to t('sign_up'), new_user_path %></li>
            <li role="presentation"><%= link_to t('sign_in'), :login %></li>
            <li role="presentation"><%= link_to t('sign_in_with_Github'), auth_at_provider_path(:provider => :github) %></li>
          <% end %>
        </ul>
      </nav>
      <h2 class="text-muted"><%= t :flashcards %></h2>
    </div>

    <div class="row">
      <div class="col-lg-2">
        <ul>
          <li><%= link_to t('listing_cards'), cards_path  %></li>
          <li><%= link_to t('listing_decks'), decks_path  %></li>
        </ul>
      </div>
      <div class="col-lg-6">
        <ul>
          <li><%= link_to t('create_card'), new_card_path %></li>
          <li><%= link_to t('create_deck'), new_deck_path %></li>
        </ul>
      </div>
    </div>
    
    <h3 class="text-center"><%= link_to t('train'), root_path %></h3>

    <p class="text-center text-success"><%= flash[:notice] %></p>
    <p class="text-center text-warning"><%= flash[:alert] %></p>

    <div class="jumbotron">
      <div class="container">
        <%= yield %>
      </div>
    </div>

  </div>

  <footer class="footer">
    <div class="container">
      <p class="text-muted">Made by Merff</p>
    </div>
  </footer>

</body>
</html>